"""empty message

Revision ID: 2f6fb5314ac8
Revises: deebdf0dfda8
Create Date: 2024-08-13 11:26:23.392809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6fb5314ac8'
down_revision = 'deebdf0dfda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('usability_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('functionality_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ratings_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=False))

    op.drop_table('ratings')
    # ### end Alembic commands ###
