"""empty message

Revision ID: deebdf0dfda8
Revises: c45bd761f941
Create Date: 2024-08-03 18:51:05.567757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deebdf0dfda8'
down_revision = 'c45bd761f941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('published_date', sa.DATETIME(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ratings', sa.INTEGER(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
